[build]
builder = "DOCKERFILE"
dockerfilePath = "boonbuilder-frontend/Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/health"
port = 80
initialDelaySeconds = 30
periodSeconds = 10